CREATE TABLE IF NOT EXISTS system_config (
  id INT PRIMARY KEY AUTO_INCREMENT,
  bloqueioAtivo BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Inserir configuração inicial
INSERT INTO system_config (bloqueioAtivo) VALUES (FALSE)
ON DUPLICATE KEY UPDATE bloqueioAtivo = bloqueioAtivo;
