// Sistema de 250 Conquistas - Seu Metro Quadrado CRM

export interface Conquista {
  id: number;
  categoria: string;
  icone: string;
  nome: string;
  descricao: string;
  meta: string;
  metaValor: number;
  metaTipo: 'ligacoes' | 'whatsapp' | 'agendamentos' | 'visitas' | 'documentacoes' | 'vendas' | 'vgv' | 'pontos' | 'dias' | 'streak' | 'ranking' | 'conquistas' | 'especial';
  pontos: number;
}

export const CONQUISTAS: Conquista[] = [
  // Categoria 1: Primeiros Passos (20 conquistas)
  { id: 1, categoria: "Primeiros Passos", icone: "🎯", nome: "Primeiro Lead", descricao: "Receba seu primeiro lead no sistema", meta: "1 lead recebido", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 2, categoria: "Primeiros Passos", icone: "📞", nome: "Primeira Ligação", descricao: "Faça sua primeira ligação para um lead", meta: "1 ligação registrada", metaValor: 1, metaTipo: "ligacoes", pontos: 10 },
  { id: 3, categoria: "Primeiros Passos", icone: "💬", nome: "Primeiro Contato", descricao: "Registre seu primeiro contato com um lead", meta: "1 contato registrado", metaValor: 1, metaTipo: "whatsapp", pontos: 10 },
  { id: 4, categoria: "Primeiros Passos", icone: "📅", nome: "Primeiro Agendamento", descricao: "Agende sua primeira visita", meta: "1 agendamento", metaValor: 1, metaTipo: "agendamentos", pontos: 15 },
  { id: 5, categoria: "Primeiros Passos", icone: "🏠", nome: "Primeira Visita", descricao: "Realize sua primeira visita com cliente", meta: "1 visita realizada", metaValor: 1, metaTipo: "visitas", pontos: 20 },
  { id: 6, categoria: "Primeiros Passos", icone: "📄", nome: "Primeira Documentação", descricao: "Envie sua primeira documentação para análise", meta: "1 documentação", metaValor: 1, metaTipo: "documentacoes", pontos: 20 },
  { id: 7, categoria: "Primeiros Passos", icone: "🎉", nome: "Primeira Venda", descricao: "Feche seu primeiro contrato", meta: "1 contrato fechado", metaValor: 1, metaTipo: "vendas", pontos: 100 },
  { id: 8, categoria: "Primeiros Passos", icone: "⭐", nome: "Perfil Completo", descricao: "Complete todas as informações do seu perfil", meta: "100% do perfil", metaValor: 100, metaTipo: "especial", pontos: 15 },
  { id: 9, categoria: "Primeiros Passos", icone: "📸", nome: "Foto de Perfil", descricao: "Adicione uma foto ao seu perfil", meta: "Foto adicionada", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 10, categoria: "Primeiros Passos", icone: "🔔", nome: "Notificações Ativas", descricao: "Ative as notificações do sistema", meta: "Notificações ativas", metaValor: 1, metaTipo: "especial", pontos: 5 },
  { id: 11, categoria: "Primeiros Passos", icone: "📱", nome: "Primeiro WhatsApp", descricao: "Envie sua primeira mensagem via WhatsApp", meta: "1 WhatsApp enviado", metaValor: 1, metaTipo: "whatsapp", pontos: 10 },
  { id: 12, categoria: "Primeiros Passos", icone: "✉️", nome: "Primeiro Email", descricao: "Envie seu primeiro email para um lead", meta: "1 email enviado", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 13, categoria: "Primeiros Passos", icone: "📝", nome: "Primeira Observação", descricao: "Adicione sua primeira observação em um lead", meta: "1 observação", metaValor: 1, metaTipo: "especial", pontos: 5 },
  { id: 14, categoria: "Primeiros Passos", icone: "🔄", nome: "Primeiro Follow-up", descricao: "Complete seu primeiro ciclo de follow-up", meta: "1 follow-up completo", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 15, categoria: "Primeiros Passos", icone: "🏆", nome: "Primeiro Ranking", descricao: "Apareça pela primeira vez no ranking", meta: "Entrar no ranking", metaValor: 1, metaTipo: "ranking", pontos: 20 },
  { id: 16, categoria: "Primeiros Passos", icone: "📊", nome: "Primeiro Dashboard", descricao: "Acesse seu dashboard de performance", meta: "Dashboard acessado", metaValor: 1, metaTipo: "especial", pontos: 5 },
  { id: 17, categoria: "Primeiros Passos", icone: "🎓", nome: "Tutorial Completo", descricao: "Complete o tutorial de boas-vindas", meta: "Tutorial 100%", metaValor: 100, metaTipo: "especial", pontos: 15 },
  { id: 18, categoria: "Primeiros Passos", icone: "🤝", nome: "Primeiro Projeto", descricao: "Conheça seu primeiro projeto/empreendimento", meta: "1 projeto visualizado", metaValor: 1, metaTipo: "especial", pontos: 5 },
  { id: 19, categoria: "Primeiros Passos", icone: "💼", nome: "Semana Completa", descricao: "Complete sua primeira semana no sistema", meta: "7 dias ativos", metaValor: 7, metaTipo: "dias", pontos: 25 },
  { id: 20, categoria: "Primeiros Passos", icone: "🌟", nome: "Mês Completo", descricao: "Complete seu primeiro mês no sistema", meta: "30 dias ativos", metaValor: 30, metaTipo: "dias", pontos: 50 },

  // Categoria 2: Mestre das Ligações (25 conquistas)
  { id: 21, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Iniciante", descricao: "Faça 10 ligações", meta: "10 ligações", metaValor: 10, metaTipo: "ligacoes", pontos: 15 },
  { id: 22, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Bronze", descricao: "Faça 25 ligações", meta: "25 ligações", metaValor: 25, metaTipo: "ligacoes", pontos: 25 },
  { id: 23, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Prata", descricao: "Faça 50 ligações", meta: "50 ligações", metaValor: 50, metaTipo: "ligacoes", pontos: 40 },
  { id: 24, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Ouro", descricao: "Faça 100 ligações", meta: "100 ligações", metaValor: 100, metaTipo: "ligacoes", pontos: 60 },
  { id: 25, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Diamante", descricao: "Faça 250 ligações", meta: "250 ligações", metaValor: 250, metaTipo: "ligacoes", pontos: 100 },
  { id: 26, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Mestre", descricao: "Faça 500 ligações", meta: "500 ligações", metaValor: 500, metaTipo: "ligacoes", pontos: 150 },
  { id: 27, categoria: "Mestre das Ligações", icone: "📞", nome: "Telefonista Lendário", descricao: "Faça 1000 ligações", meta: "1000 ligações", metaValor: 1000, metaTipo: "ligacoes", pontos: 250 },
  { id: 28, categoria: "Mestre das Ligações", icone: "📞", nome: "Maratonista Diário", descricao: "Faça 20 ligações em um dia", meta: "20 ligações/dia", metaValor: 20, metaTipo: "ligacoes", pontos: 30 },
  { id: 29, categoria: "Mestre das Ligações", icone: "📞", nome: "Maratonista Semanal", descricao: "Faça 100 ligações em uma semana", meta: "100 ligações/semana", metaValor: 100, metaTipo: "ligacoes", pontos: 50 },
  { id: 30, categoria: "Mestre das Ligações", icone: "📞", nome: "Maratonista Mensal", descricao: "Faça 400 ligações em um mês", meta: "400 ligações/mês", metaValor: 400, metaTipo: "ligacoes", pontos: 100 },
  { id: 31, categoria: "Mestre das Ligações", icone: "📞", nome: "Streak de Ligações 3", descricao: "Faça ligações por 3 dias consecutivos", meta: "3 dias seguidos", metaValor: 3, metaTipo: "streak", pontos: 20 },
  { id: 32, categoria: "Mestre das Ligações", icone: "📞", nome: "Streak de Ligações 7", descricao: "Faça ligações por 7 dias consecutivos", meta: "7 dias seguidos", metaValor: 7, metaTipo: "streak", pontos: 40 },
  { id: 33, categoria: "Mestre das Ligações", icone: "📞", nome: "Streak de Ligações 14", descricao: "Faça ligações por 14 dias consecutivos", meta: "14 dias seguidos", metaValor: 14, metaTipo: "streak", pontos: 70 },
  { id: 34, categoria: "Mestre das Ligações", icone: "📞", nome: "Streak de Ligações 30", descricao: "Faça ligações por 30 dias consecutivos", meta: "30 dias seguidos", metaValor: 30, metaTipo: "streak", pontos: 150 },
  { id: 35, categoria: "Mestre das Ligações", icone: "📞", nome: "Ligação Matinal", descricao: "Faça uma ligação antes das 9h", meta: "1 ligação antes 9h", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 36, categoria: "Mestre das Ligações", icone: "📞", nome: "Ligação Noturna", descricao: "Faça uma ligação após as 18h", meta: "1 ligação após 18h", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 37, categoria: "Mestre das Ligações", icone: "📞", nome: "Ligação de Sábado", descricao: "Faça uma ligação no sábado", meta: "1 ligação sábado", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 38, categoria: "Mestre das Ligações", icone: "📞", nome: "Conversão por Ligação", descricao: "Converta um lead após ligação", meta: "1 conversão", metaValor: 1, metaTipo: "vendas", pontos: 50 },
  { id: 39, categoria: "Mestre das Ligações", icone: "📞", nome: "5 Conversões por Ligação", descricao: "Converta 5 leads após ligação", meta: "5 conversões", metaValor: 5, metaTipo: "vendas", pontos: 100 },
  { id: 40, categoria: "Mestre das Ligações", icone: "📞", nome: "10 Conversões por Ligação", descricao: "Converta 10 leads após ligação", meta: "10 conversões", metaValor: 10, metaTipo: "vendas", pontos: 200 },
  { id: 41, categoria: "Mestre das Ligações", icone: "📞", nome: "Ligação Relâmpago", descricao: "Ligue para lead em menos de 5 min", meta: "Resposta < 5 min", metaValor: 1, metaTipo: "especial", pontos: 25 },
  { id: 42, categoria: "Mestre das Ligações", icone: "📞", nome: "10 Ligações Relâmpago", descricao: "10 ligações em menos de 5 min", meta: "10 respostas rápidas", metaValor: 10, metaTipo: "especial", pontos: 75 },
  { id: 43, categoria: "Mestre das Ligações", icone: "📞", nome: "Persistente", descricao: "Ligue 5 vezes para o mesmo lead", meta: "5 tentativas", metaValor: 5, metaTipo: "especial", pontos: 20 },
  { id: 44, categoria: "Mestre das Ligações", icone: "📞", nome: "Muito Persistente", descricao: "Ligue 10 vezes para o mesmo lead", meta: "10 tentativas", metaValor: 10, metaTipo: "especial", pontos: 40 },
  { id: 45, categoria: "Mestre das Ligações", icone: "📞", nome: "Rei do Telefone", descricao: "Seja o corretor com mais ligações do mês", meta: "#1 em ligações", metaValor: 1, metaTipo: "ranking", pontos: 200 },

  // Categoria 3: Mestre do WhatsApp (25 conquistas)
  { id: 46, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Iniciante", descricao: "Envie 10 mensagens", meta: "10 mensagens", metaValor: 10, metaTipo: "whatsapp", pontos: 15 },
  { id: 47, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Bronze", descricao: "Envie 25 mensagens", meta: "25 mensagens", metaValor: 25, metaTipo: "whatsapp", pontos: 25 },
  { id: 48, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Prata", descricao: "Envie 50 mensagens", meta: "50 mensagens", metaValor: 50, metaTipo: "whatsapp", pontos: 40 },
  { id: 49, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Ouro", descricao: "Envie 100 mensagens", meta: "100 mensagens", metaValor: 100, metaTipo: "whatsapp", pontos: 60 },
  { id: 50, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Diamante", descricao: "Envie 250 mensagens", meta: "250 mensagens", metaValor: 250, metaTipo: "whatsapp", pontos: 100 },
  { id: 51, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Mestre", descricao: "Envie 500 mensagens", meta: "500 mensagens", metaValor: 500, metaTipo: "whatsapp", pontos: 150 },
  { id: 52, categoria: "Mestre do WhatsApp", icone: "💬", nome: "WhatsApp Lendário", descricao: "Envie 1000 mensagens", meta: "1000 mensagens", metaValor: 1000, metaTipo: "whatsapp", pontos: 250 },
  { id: 53, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Resposta Rápida", descricao: "Responda lead em menos de 1 minuto", meta: "Resposta < 1 min", metaValor: 1, metaTipo: "especial", pontos: 30 },
  { id: 54, categoria: "Mestre do WhatsApp", icone: "💬", nome: "10 Respostas Rápidas", descricao: "10 respostas em menos de 1 minuto", meta: "10 respostas < 1 min", metaValor: 10, metaTipo: "especial", pontos: 100 },
  { id: 55, categoria: "Mestre do WhatsApp", icone: "💬", nome: "50 Respostas Rápidas", descricao: "50 respostas em menos de 1 minuto", meta: "50 respostas < 1 min", metaValor: 50, metaTipo: "especial", pontos: 200 },
  { id: 56, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Conversão por WhatsApp", descricao: "Converta um lead via WhatsApp", meta: "1 conversão", metaValor: 1, metaTipo: "vendas", pontos: 50 },
  { id: 57, categoria: "Mestre do WhatsApp", icone: "💬", nome: "5 Conversões WhatsApp", descricao: "Converta 5 leads via WhatsApp", meta: "5 conversões", metaValor: 5, metaTipo: "vendas", pontos: 100 },
  { id: 58, categoria: "Mestre do WhatsApp", icone: "💬", nome: "10 Conversões WhatsApp", descricao: "Converta 10 leads via WhatsApp", meta: "10 conversões", metaValor: 10, metaTipo: "vendas", pontos: 200 },
  { id: 59, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Streak WhatsApp 3", descricao: "Envie mensagens por 3 dias seguidos", meta: "3 dias seguidos", metaValor: 3, metaTipo: "streak", pontos: 20 },
  { id: 60, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Streak WhatsApp 7", descricao: "Envie mensagens por 7 dias seguidos", meta: "7 dias seguidos", metaValor: 7, metaTipo: "streak", pontos: 40 },
  { id: 61, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Streak WhatsApp 14", descricao: "Envie mensagens por 14 dias seguidos", meta: "14 dias seguidos", metaValor: 14, metaTipo: "streak", pontos: 70 },
  { id: 62, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Streak WhatsApp 30", descricao: "Envie mensagens por 30 dias seguidos", meta: "30 dias seguidos", metaValor: 30, metaTipo: "streak", pontos: 150 },
  { id: 63, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Madrugador WhatsApp", descricao: "Envie mensagem antes das 8h", meta: "1 msg antes 8h", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 64, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Coruja WhatsApp", descricao: "Envie mensagem após as 21h", meta: "1 msg após 21h", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 65, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Fim de Semana Ativo", descricao: "Envie mensagem no fim de semana", meta: "1 msg fim de semana", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 66, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Multitarefa WhatsApp", descricao: "Envie 10 mensagens em 1 hora", meta: "10 msg/hora", metaValor: 10, metaTipo: "especial", pontos: 25 },
  { id: 67, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Rei do WhatsApp", descricao: "Seja #1 em mensagens do mês", meta: "#1 em mensagens", metaValor: 1, metaTipo: "ranking", pontos: 200 },
  { id: 68, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Áudio Master", descricao: "Envie 10 áudios para leads", meta: "10 áudios", metaValor: 10, metaTipo: "especial", pontos: 30 },
  { id: 69, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Foto Enviada", descricao: "Envie 10 fotos de projetos", meta: "10 fotos", metaValor: 10, metaTipo: "especial", pontos: 30 },
  { id: 70, categoria: "Mestre do WhatsApp", icone: "💬", nome: "Vídeo Enviado", descricao: "Envie 5 vídeos de projetos", meta: "5 vídeos", metaValor: 5, metaTipo: "especial", pontos: 40 },

  // Categoria 4: Agendador Profissional (25 conquistas)
  { id: 71, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Iniciante", descricao: "Agende 5 visitas", meta: "5 agendamentos", metaValor: 5, metaTipo: "agendamentos", pontos: 20 },
  { id: 72, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Bronze", descricao: "Agende 10 visitas", meta: "10 agendamentos", metaValor: 10, metaTipo: "agendamentos", pontos: 35 },
  { id: 73, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Prata", descricao: "Agende 25 visitas", meta: "25 agendamentos", metaValor: 25, metaTipo: "agendamentos", pontos: 60 },
  { id: 74, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Ouro", descricao: "Agende 50 visitas", meta: "50 agendamentos", metaValor: 50, metaTipo: "agendamentos", pontos: 100 },
  { id: 75, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Diamante", descricao: "Agende 100 visitas", meta: "100 agendamentos", metaValor: 100, metaTipo: "agendamentos", pontos: 175 },
  { id: 76, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Mestre", descricao: "Agende 200 visitas", meta: "200 agendamentos", metaValor: 200, metaTipo: "agendamentos", pontos: 300 },
  { id: 77, categoria: "Agendador Profissional", icone: "📅", nome: "Agendador Lendário", descricao: "Agende 500 visitas", meta: "500 agendamentos", metaValor: 500, metaTipo: "agendamentos", pontos: 500 },
  { id: 78, categoria: "Agendador Profissional", icone: "📅", nome: "Dia Cheio", descricao: "Agende 5 visitas em um dia", meta: "5 agend/dia", metaValor: 5, metaTipo: "agendamentos", pontos: 50 },
  { id: 79, categoria: "Agendador Profissional", icone: "📅", nome: "Semana Cheia", descricao: "Agende 15 visitas em uma semana", meta: "15 agend/semana", metaValor: 15, metaTipo: "agendamentos", pontos: 75 },
  { id: 80, categoria: "Agendador Profissional", icone: "📅", nome: "Mês Cheio", descricao: "Agende 50 visitas em um mês", meta: "50 agend/mês", metaValor: 50, metaTipo: "agendamentos", pontos: 150 },
  { id: 81, categoria: "Agendador Profissional", icone: "📅", nome: "Streak Agendamentos 3", descricao: "Agende por 3 dias consecutivos", meta: "3 dias seguidos", metaValor: 3, metaTipo: "streak", pontos: 25 },
  { id: 82, categoria: "Agendador Profissional", icone: "📅", nome: "Streak Agendamentos 7", descricao: "Agende por 7 dias consecutivos", meta: "7 dias seguidos", metaValor: 7, metaTipo: "streak", pontos: 50 },
  { id: 83, categoria: "Agendador Profissional", icone: "📅", nome: "Streak Agendamentos 14", descricao: "Agende por 14 dias consecutivos", meta: "14 dias seguidos", metaValor: 14, metaTipo: "streak", pontos: 100 },
  { id: 84, categoria: "Agendador Profissional", icone: "📅", nome: "Agendamento Matinal", descricao: "Agende visita para manhã", meta: "1 agend manhã", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 85, categoria: "Agendador Profissional", icone: "📅", nome: "Agendamento Tarde", descricao: "Agende visita para tarde", meta: "1 agend tarde", metaValor: 1, metaTipo: "especial", pontos: 10 },
  { id: 86, categoria: "Agendador Profissional", icone: "📅", nome: "Agendamento Noite", descricao: "Agende visita para noite", meta: "1 agend noite", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 87, categoria: "Agendador Profissional", icone: "📅", nome: "Agendamento Sábado", descricao: "Agende visita para sábado", meta: "1 agend sábado", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 88, categoria: "Agendador Profissional", icone: "📅", nome: "Agendamento Domingo", descricao: "Agende visita para domingo", meta: "1 agend domingo", metaValor: 1, metaTipo: "especial", pontos: 20 },
  { id: 89, categoria: "Agendador Profissional", icone: "📅", nome: "Conversão Agendamento", descricao: "Converta agendamento em venda", meta: "1 conversão", metaValor: 1, metaTipo: "vendas", pontos: 75 },
  { id: 90, categoria: "Agendador Profissional", icone: "📅", nome: "5 Conversões Agendamento", descricao: "Converta 5 agendamentos", meta: "5 conversões", metaValor: 5, metaTipo: "vendas", pontos: 150 },
  { id: 91, categoria: "Agendador Profissional", icone: "📅", nome: "10 Conversões Agendamento", descricao: "Converta 10 agendamentos", meta: "10 conversões", metaValor: 10, metaTipo: "vendas", pontos: 300 },
  { id: 92, categoria: "Agendador Profissional", icone: "📅", nome: "Taxa 50% Agendamento", descricao: "Mantenha 50% de conversão", meta: "50% taxa", metaValor: 50, metaTipo: "especial", pontos: 100 },
  { id: 93, categoria: "Agendador Profissional", icone: "📅", nome: "Taxa 75% Agendamento", descricao: "Mantenha 75% de conversão", meta: "75% taxa", metaValor: 75, metaTipo: "especial", pontos: 200 },
  { id: 94, categoria: "Agendador Profissional", icone: "📅", nome: "Rei dos Agendamentos", descricao: "Seja #1 em agendamentos do mês", meta: "#1 agendamentos", metaValor: 1, metaTipo: "ranking", pontos: 200 },
  { id: 95, categoria: "Agendador Profissional", icone: "📅", nome: "Agenda Organizada", descricao: "Tenha 10 agendamentos futuros", meta: "10 agend futuros", metaValor: 10, metaTipo: "especial", pontos: 50 },

  // Categoria 5: Visitador Expert (25 conquistas)
  { id: 96, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Iniciante", descricao: "Realize 5 visitas", meta: "5 visitas", metaValor: 5, metaTipo: "visitas", pontos: 25 },
  { id: 97, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Bronze", descricao: "Realize 10 visitas", meta: "10 visitas", metaValor: 10, metaTipo: "visitas", pontos: 45 },
  { id: 98, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Prata", descricao: "Realize 25 visitas", meta: "25 visitas", metaValor: 25, metaTipo: "visitas", pontos: 80 },
  { id: 99, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Ouro", descricao: "Realize 50 visitas", meta: "50 visitas", metaValor: 50, metaTipo: "visitas", pontos: 125 },
  { id: 100, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Diamante", descricao: "Realize 100 visitas", meta: "100 visitas", metaValor: 100, metaTipo: "visitas", pontos: 200 },
  { id: 101, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Mestre", descricao: "Realize 200 visitas", meta: "200 visitas", metaValor: 200, metaTipo: "visitas", pontos: 350 },
  { id: 102, categoria: "Visitador Expert", icone: "🏠", nome: "Visitador Lendário", descricao: "Realize 500 visitas", meta: "500 visitas", metaValor: 500, metaTipo: "visitas", pontos: 600 },
  { id: 103, categoria: "Visitador Expert", icone: "🏠", nome: "Dia de Visitas", descricao: "Realize 3 visitas em um dia", meta: "3 visitas/dia", metaValor: 3, metaTipo: "visitas", pontos: 40 },
  { id: 104, categoria: "Visitador Expert", icone: "🏠", nome: "Semana de Visitas", descricao: "Realize 10 visitas em uma semana", meta: "10 visitas/semana", metaValor: 10, metaTipo: "visitas", pontos: 75 },
  { id: 105, categoria: "Visitador Expert", icone: "🏠", nome: "Mês de Visitas", descricao: "Realize 30 visitas em um mês", meta: "30 visitas/mês", metaValor: 30, metaTipo: "visitas", pontos: 150 },
  { id: 106, categoria: "Visitador Expert", icone: "🏠", nome: "Streak Visitas 3", descricao: "Visite por 3 dias consecutivos", meta: "3 dias seguidos", metaValor: 3, metaTipo: "streak", pontos: 30 },
  { id: 107, categoria: "Visitador Expert", icone: "🏠", nome: "Streak Visitas 7", descricao: "Visite por 7 dias consecutivos", meta: "7 dias seguidos", metaValor: 7, metaTipo: "streak", pontos: 60 },
  { id: 108, categoria: "Visitador Expert", icone: "🏠", nome: "Streak Visitas 14", descricao: "Visite por 14 dias consecutivos", meta: "14 dias seguidos", metaValor: 14, metaTipo: "streak", pontos: 120 },
  { id: 109, categoria: "Visitador Expert", icone: "🏠", nome: "Visita Matinal", descricao: "Realize visita antes das 10h", meta: "1 visita manhã", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 110, categoria: "Visitador Expert", icone: "🏠", nome: "Visita Noturna", descricao: "Realize visita após as 18h", meta: "1 visita noite", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 111, categoria: "Visitador Expert", icone: "🏠", nome: "Visita Fim de Semana", descricao: "Realize visita no fim de semana", meta: "1 visita fds", metaValor: 1, metaTipo: "especial", pontos: 20 },
  { id: 112, categoria: "Visitador Expert", icone: "🏠", nome: "Conversão Visita", descricao: "Converta visita em venda", meta: "1 conversão", metaValor: 1, metaTipo: "vendas", pontos: 100 },
  { id: 113, categoria: "Visitador Expert", icone: "🏠", nome: "5 Conversões Visita", descricao: "Converta 5 visitas em vendas", meta: "5 conversões", metaValor: 5, metaTipo: "vendas", pontos: 200 },
  { id: 114, categoria: "Visitador Expert", icone: "🏠", nome: "10 Conversões Visita", descricao: "Converta 10 visitas em vendas", meta: "10 conversões", metaValor: 10, metaTipo: "vendas", pontos: 400 },
  { id: 115, categoria: "Visitador Expert", icone: "🏠", nome: "Taxa 25% Visita", descricao: "Mantenha 25% de conversão", meta: "25% taxa", metaValor: 25, metaTipo: "especial", pontos: 75 },
  { id: 116, categoria: "Visitador Expert", icone: "🏠", nome: "Taxa 50% Visita", descricao: "Mantenha 50% de conversão", meta: "50% taxa", metaValor: 50, metaTipo: "especial", pontos: 150 },
  { id: 117, categoria: "Visitador Expert", icone: "🏠", nome: "Taxa 75% Visita", descricao: "Mantenha 75% de conversão", meta: "75% taxa", metaValor: 75, metaTipo: "especial", pontos: 300 },
  { id: 118, categoria: "Visitador Expert", icone: "🏠", nome: "Rei das Visitas", descricao: "Seja #1 em visitas do mês", meta: "#1 visitas", metaValor: 1, metaTipo: "ranking", pontos: 200 },
  { id: 119, categoria: "Visitador Expert", icone: "🏠", nome: "Explorador", descricao: "Visite 5 projetos diferentes", meta: "5 projetos", metaValor: 5, metaTipo: "especial", pontos: 50 },
  { id: 120, categoria: "Visitador Expert", icone: "🏠", nome: "Grande Explorador", descricao: "Visite 10 projetos diferentes", meta: "10 projetos", metaValor: 10, metaTipo: "especial", pontos: 100 },

  // Categoria 6: Documentador (20 conquistas)
  { id: 121, categoria: "Documentador", icone: "📄", nome: "Documentador Iniciante", descricao: "Envie 5 documentações", meta: "5 docs", metaValor: 5, metaTipo: "documentacoes", pontos: 30 },
  { id: 122, categoria: "Documentador", icone: "📄", nome: "Documentador Bronze", descricao: "Envie 10 documentações", meta: "10 docs", metaValor: 10, metaTipo: "documentacoes", pontos: 50 },
  { id: 123, categoria: "Documentador", icone: "📄", nome: "Documentador Prata", descricao: "Envie 25 documentações", meta: "25 docs", metaValor: 25, metaTipo: "documentacoes", pontos: 90 },
  { id: 124, categoria: "Documentador", icone: "📄", nome: "Documentador Ouro", descricao: "Envie 50 documentações", meta: "50 docs", metaValor: 50, metaTipo: "documentacoes", pontos: 150 },
  { id: 125, categoria: "Documentador", icone: "📄", nome: "Documentador Diamante", descricao: "Envie 100 documentações", meta: "100 docs", metaValor: 100, metaTipo: "documentacoes", pontos: 250 },
  { id: 126, categoria: "Documentador", icone: "📄", nome: "Documentador Mestre", descricao: "Envie 200 documentações", meta: "200 docs", metaValor: 200, metaTipo: "documentacoes", pontos: 400 },
  { id: 127, categoria: "Documentador", icone: "📄", nome: "Documentador Lendário", descricao: "Envie 500 documentações", meta: "500 docs", metaValor: 500, metaTipo: "documentacoes", pontos: 700 },
  { id: 128, categoria: "Documentador", icone: "📄", nome: "Dia de Docs", descricao: "Envie 3 documentações em um dia", meta: "3 docs/dia", metaValor: 3, metaTipo: "documentacoes", pontos: 50 },
  { id: 129, categoria: "Documentador", icone: "📄", nome: "Semana de Docs", descricao: "Envie 10 documentações em uma semana", meta: "10 docs/semana", metaValor: 10, metaTipo: "documentacoes", pontos: 100 },
  { id: 130, categoria: "Documentador", icone: "📄", nome: "Mês de Docs", descricao: "Envie 25 documentações em um mês", meta: "25 docs/mês", metaValor: 25, metaTipo: "documentacoes", pontos: 200 },
  { id: 131, categoria: "Documentador", icone: "📄", nome: "Doc Aprovada", descricao: "Tenha documentação aprovada", meta: "1 aprovação", metaValor: 1, metaTipo: "especial", pontos: 75 },
  { id: 132, categoria: "Documentador", icone: "📄", nome: "5 Docs Aprovadas", descricao: "Tenha 5 documentações aprovadas", meta: "5 aprovações", metaValor: 5, metaTipo: "especial", pontos: 150 },
  { id: 133, categoria: "Documentador", icone: "📄", nome: "10 Docs Aprovadas", descricao: "Tenha 10 documentações aprovadas", meta: "10 aprovações", metaValor: 10, metaTipo: "especial", pontos: 300 },
  { id: 134, categoria: "Documentador", icone: "📄", nome: "25 Docs Aprovadas", descricao: "Tenha 25 documentações aprovadas", meta: "25 aprovações", metaValor: 25, metaTipo: "especial", pontos: 500 },
  { id: 135, categoria: "Documentador", icone: "📄", nome: "Taxa 50% Aprovação", descricao: "Mantenha 50% de aprovação", meta: "50% taxa", metaValor: 50, metaTipo: "especial", pontos: 100 },
  { id: 136, categoria: "Documentador", icone: "📄", nome: "Taxa 75% Aprovação", descricao: "Mantenha 75% de aprovação", meta: "75% taxa", metaValor: 75, metaTipo: "especial", pontos: 200 },
  { id: 137, categoria: "Documentador", icone: "📄", nome: "Taxa 90% Aprovação", descricao: "Mantenha 90% de aprovação", meta: "90% taxa", metaValor: 90, metaTipo: "especial", pontos: 400 },
  { id: 138, categoria: "Documentador", icone: "📄", nome: "Rei da Documentação", descricao: "Seja #1 em docs do mês", meta: "#1 docs", metaValor: 1, metaTipo: "ranking", pontos: 200 },
  { id: 139, categoria: "Documentador", icone: "📄", nome: "Doc Relâmpago", descricao: "Envie doc no mesmo dia da visita", meta: "Doc < 24h", metaValor: 1, metaTipo: "especial", pontos: 50 },
  { id: 140, categoria: "Documentador", icone: "📄", nome: "10 Docs Relâmpago", descricao: "10 docs no mesmo dia da visita", meta: "10 docs < 24h", metaValor: 10, metaTipo: "especial", pontos: 150 },

  // Categoria 7: Vendedor Campeão (30 conquistas)
  { id: 141, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Iniciante", descricao: "Feche 3 contratos", meta: "3 vendas", metaValor: 3, metaTipo: "vendas", pontos: 100 },
  { id: 142, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Bronze", descricao: "Feche 5 contratos", meta: "5 vendas", metaValor: 5, metaTipo: "vendas", pontos: 150 },
  { id: 143, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Prata", descricao: "Feche 10 contratos", meta: "10 vendas", metaValor: 10, metaTipo: "vendas", pontos: 250 },
  { id: 144, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Ouro", descricao: "Feche 25 contratos", meta: "25 vendas", metaValor: 25, metaTipo: "vendas", pontos: 500 },
  { id: 145, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Diamante", descricao: "Feche 50 contratos", meta: "50 vendas", metaValor: 50, metaTipo: "vendas", pontos: 1000 },
  { id: 146, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Mestre", descricao: "Feche 100 contratos", meta: "100 vendas", metaValor: 100, metaTipo: "vendas", pontos: 2000 },
  { id: 147, categoria: "Vendedor Campeão", icone: "🏆", nome: "Vendedor Lendário", descricao: "Feche 250 contratos", meta: "250 vendas", metaValor: 250, metaTipo: "vendas", pontos: 5000 },
  { id: 148, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 100K", descricao: "Atinja R$ 100.000 em VGV", meta: "R$ 100K", metaValor: 100000, metaTipo: "vgv", pontos: 100 },
  { id: 149, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 250K", descricao: "Atinja R$ 250.000 em VGV", meta: "R$ 250K", metaValor: 250000, metaTipo: "vgv", pontos: 200 },
  { id: 150, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 500K", descricao: "Atinja R$ 500.000 em VGV", meta: "R$ 500K", metaValor: 500000, metaTipo: "vgv", pontos: 400 },
  { id: 151, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 1M", descricao: "Atinja R$ 1.000.000 em VGV", meta: "R$ 1M", metaValor: 1000000, metaTipo: "vgv", pontos: 750 },
  { id: 152, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 2.5M", descricao: "Atinja R$ 2.500.000 em VGV", meta: "R$ 2.5M", metaValor: 2500000, metaTipo: "vgv", pontos: 1500 },
  { id: 153, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 5M", descricao: "Atinja R$ 5.000.000 em VGV", meta: "R$ 5M", metaValor: 5000000, metaTipo: "vgv", pontos: 3000 },
  { id: 154, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 10M", descricao: "Atinja R$ 10.000.000 em VGV", meta: "R$ 10M", metaValor: 10000000, metaTipo: "vgv", pontos: 6000 },
  { id: 155, categoria: "Vendedor Campeão", icone: "💰", nome: "VGV 25M", descricao: "Atinja R$ 25.000.000 em VGV", meta: "R$ 25M", metaValor: 25000000, metaTipo: "vgv", pontos: 15000 },
  { id: 156, categoria: "Vendedor Campeão", icone: "🎯", nome: "Venda Semanal", descricao: "Feche 1 venda na semana", meta: "1 venda/semana", metaValor: 1, metaTipo: "vendas", pontos: 50 },
  { id: 157, categoria: "Vendedor Campeão", icone: "🎯", nome: "2 Vendas Semanais", descricao: "Feche 2 vendas na semana", meta: "2 vendas/semana", metaValor: 2, metaTipo: "vendas", pontos: 100 },
  { id: 158, categoria: "Vendedor Campeão", icone: "🎯", nome: "3 Vendas Semanais", descricao: "Feche 3 vendas na semana", meta: "3 vendas/semana", metaValor: 3, metaTipo: "vendas", pontos: 175 },
  { id: 159, categoria: "Vendedor Campeão", icone: "🎯", nome: "Venda Mensal", descricao: "Feche 1 venda no mês", meta: "1 venda/mês", metaValor: 1, metaTipo: "vendas", pontos: 75 },
  { id: 160, categoria: "Vendedor Campeão", icone: "🎯", nome: "3 Vendas Mensais", descricao: "Feche 3 vendas no mês", meta: "3 vendas/mês", metaValor: 3, metaTipo: "vendas", pontos: 150 },
  { id: 161, categoria: "Vendedor Campeão", icone: "🎯", nome: "5 Vendas Mensais", descricao: "Feche 5 vendas no mês", meta: "5 vendas/mês", metaValor: 5, metaTipo: "vendas", pontos: 250 },
  { id: 162, categoria: "Vendedor Campeão", icone: "🎯", nome: "10 Vendas Mensais", descricao: "Feche 10 vendas no mês", meta: "10 vendas/mês", metaValor: 10, metaTipo: "vendas", pontos: 500 },
  { id: 163, categoria: "Vendedor Campeão", icone: "🔥", nome: "Streak Vendas 2", descricao: "Venda por 2 semanas seguidas", meta: "2 semanas", metaValor: 2, metaTipo: "streak", pontos: 100 },
  { id: 164, categoria: "Vendedor Campeão", icone: "🔥", nome: "Streak Vendas 4", descricao: "Venda por 4 semanas seguidas", meta: "4 semanas", metaValor: 4, metaTipo: "streak", pontos: 250 },
  { id: 165, categoria: "Vendedor Campeão", icone: "🔥", nome: "Streak Vendas 8", descricao: "Venda por 8 semanas seguidas", meta: "8 semanas", metaValor: 8, metaTipo: "streak", pontos: 500 },
  { id: 166, categoria: "Vendedor Campeão", icone: "🔥", nome: "Streak Vendas 12", descricao: "Venda por 12 semanas seguidas", meta: "12 semanas", metaValor: 12, metaTipo: "streak", pontos: 1000 },
  { id: 167, categoria: "Vendedor Campeão", icone: "👑", nome: "Top 3 Semanal", descricao: "Fique no top 3 da semana", meta: "Top 3 semana", metaValor: 3, metaTipo: "ranking", pontos: 75 },
  { id: 168, categoria: "Vendedor Campeão", icone: "👑", nome: "Top 3 Mensal", descricao: "Fique no top 3 do mês", meta: "Top 3 mês", metaValor: 3, metaTipo: "ranking", pontos: 150 },
  { id: 169, categoria: "Vendedor Campeão", icone: "👑", nome: "Campeão Semanal", descricao: "Seja #1 da semana", meta: "#1 semana", metaValor: 1, metaTipo: "ranking", pontos: 200 },
  { id: 170, categoria: "Vendedor Campeão", icone: "👑", nome: "Campeão Mensal", descricao: "Seja #1 do mês", meta: "#1 mês", metaValor: 1, metaTipo: "ranking", pontos: 500 },

  // Categoria 8: Metas e Objetivos (25 conquistas)
  { id: 171, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Diária Ligações", descricao: "Bata a meta diária de ligações", meta: "Meta ligações", metaValor: 1, metaTipo: "especial", pontos: 20 },
  { id: 172, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Diária Contatos", descricao: "Bata a meta diária de contatos", meta: "Meta contatos", metaValor: 1, metaTipo: "especial", pontos: 20 },
  { id: 173, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Diária Agendamentos", descricao: "Bata a meta diária de agendamentos", meta: "Meta agendamentos", metaValor: 1, metaTipo: "especial", pontos: 30 },
  { id: 174, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Diária Visitas", descricao: "Bata a meta diária de visitas", meta: "Meta visitas", metaValor: 1, metaTipo: "especial", pontos: 40 },
  { id: 175, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Diária Docs", descricao: "Bata a meta diária de documentações", meta: "Meta docs", metaValor: 1, metaTipo: "especial", pontos: 40 },
  { id: 176, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Semanal Ligações", descricao: "Bata a meta semanal de ligações", meta: "Meta sem ligações", metaValor: 1, metaTipo: "especial", pontos: 50 },
  { id: 177, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Semanal Contatos", descricao: "Bata a meta semanal de contatos", meta: "Meta sem contatos", metaValor: 1, metaTipo: "especial", pontos: 50 },
  { id: 178, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Semanal Agendamentos", descricao: "Bata a meta semanal de agendamentos", meta: "Meta sem agend", metaValor: 1, metaTipo: "especial", pontos: 75 },
  { id: 179, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Semanal Visitas", descricao: "Bata a meta semanal de visitas", meta: "Meta sem visitas", metaValor: 1, metaTipo: "especial", pontos: 100 },
  { id: 180, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Semanal Vendas", descricao: "Bata a meta semanal de vendas", meta: "Meta sem vendas", metaValor: 1, metaTipo: "especial", pontos: 150 },
  { id: 181, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Mensal Ligações", descricao: "Bata a meta mensal de ligações", meta: "Meta mês ligações", metaValor: 1, metaTipo: "especial", pontos: 100 },
  { id: 182, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Mensal Contatos", descricao: "Bata a meta mensal de contatos", meta: "Meta mês contatos", metaValor: 1, metaTipo: "especial", pontos: 100 },
  { id: 183, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Mensal Agendamentos", descricao: "Bata a meta mensal de agendamentos", meta: "Meta mês agend", metaValor: 1, metaTipo: "especial", pontos: 150 },
  { id: 184, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Mensal Visitas", descricao: "Bata a meta mensal de visitas", meta: "Meta mês visitas", metaValor: 1, metaTipo: "especial", pontos: 200 },
  { id: 185, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Mensal Vendas", descricao: "Bata a meta mensal de vendas", meta: "Meta mês vendas", metaValor: 1, metaTipo: "especial", pontos: 300 },
  { id: 186, categoria: "Metas e Objetivos", icone: "🎯", nome: "Meta Mensal VGV", descricao: "Bata a meta mensal de VGV", meta: "Meta mês VGV", metaValor: 1, metaTipo: "especial", pontos: 400 },
  { id: 187, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Diária 3", descricao: "Bata meta diária por 3 dias", meta: "3 dias meta", metaValor: 3, metaTipo: "streak", pontos: 50 },
  { id: 188, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Diária 7", descricao: "Bata meta diária por 7 dias", meta: "7 dias meta", metaValor: 7, metaTipo: "streak", pontos: 100 },
  { id: 189, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Diária 14", descricao: "Bata meta diária por 14 dias", meta: "14 dias meta", metaValor: 14, metaTipo: "streak", pontos: 200 },
  { id: 190, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Diária 30", descricao: "Bata meta diária por 30 dias", meta: "30 dias meta", metaValor: 30, metaTipo: "streak", pontos: 500 },
  { id: 191, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Semanal 2", descricao: "Bata meta semanal por 2 semanas", meta: "2 semanas meta", metaValor: 2, metaTipo: "streak", pontos: 100 },
  { id: 192, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Semanal 4", descricao: "Bata meta semanal por 4 semanas", meta: "4 semanas meta", metaValor: 4, metaTipo: "streak", pontos: 250 },
  { id: 193, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Mensal 2", descricao: "Bata meta mensal por 2 meses", meta: "2 meses meta", metaValor: 2, metaTipo: "streak", pontos: 300 },
  { id: 194, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Mensal 3", descricao: "Bata meta mensal por 3 meses", meta: "3 meses meta", metaValor: 3, metaTipo: "streak", pontos: 500 },
  { id: 195, categoria: "Metas e Objetivos", icone: "🔥", nome: "Streak Meta Mensal 6", descricao: "Bata meta mensal por 6 meses", meta: "6 meses meta", metaValor: 6, metaTipo: "streak", pontos: 1000 },

  // Categoria 9: Produtividade (25 conquistas)
  { id: 196, categoria: "Produtividade", icone: "⚡", nome: "Dia Produtivo", descricao: "Atinja 100 pontos em um dia", meta: "100 pts/dia", metaValor: 100, metaTipo: "pontos", pontos: 30 },
  { id: 197, categoria: "Produtividade", icone: "⚡", nome: "Dia Super Produtivo", descricao: "Atinja 200 pontos em um dia", meta: "200 pts/dia", metaValor: 200, metaTipo: "pontos", pontos: 60 },
  { id: 198, categoria: "Produtividade", icone: "⚡", nome: "Dia Ultra Produtivo", descricao: "Atinja 300 pontos em um dia", meta: "300 pts/dia", metaValor: 300, metaTipo: "pontos", pontos: 100 },
  { id: 199, categoria: "Produtividade", icone: "⚡", nome: "Semana Produtiva", descricao: "Atinja 500 pontos na semana", meta: "500 pts/semana", metaValor: 500, metaTipo: "pontos", pontos: 75 },
  { id: 200, categoria: "Produtividade", icone: "⚡", nome: "Semana Super Produtiva", descricao: "Atinja 1000 pontos na semana", meta: "1000 pts/semana", metaValor: 1000, metaTipo: "pontos", pontos: 150 },
  { id: 201, categoria: "Produtividade", icone: "⚡", nome: "Mês Produtivo", descricao: "Atinja 2000 pontos no mês", meta: "2000 pts/mês", metaValor: 2000, metaTipo: "pontos", pontos: 200 },
  { id: 202, categoria: "Produtividade", icone: "⚡", nome: "Mês Super Produtivo", descricao: "Atinja 5000 pontos no mês", meta: "5000 pts/mês", metaValor: 5000, metaTipo: "pontos", pontos: 400 },
  { id: 203, categoria: "Produtividade", icone: "⚡", nome: "Mês Ultra Produtivo", descricao: "Atinja 10000 pontos no mês", meta: "10000 pts/mês", metaValor: 10000, metaTipo: "pontos", pontos: 800 },
  { id: 204, categoria: "Produtividade", icone: "🌅", nome: "Madrugador", descricao: "Registre atividade antes das 8h", meta: "Atividade < 8h", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 205, categoria: "Produtividade", icone: "🌅", nome: "10x Madrugador", descricao: "10 atividades antes das 8h", meta: "10 ativ < 8h", metaValor: 10, metaTipo: "especial", pontos: 50 },
  { id: 206, categoria: "Produtividade", icone: "🌙", nome: "Coruja", descricao: "Registre atividade após as 20h", meta: "Atividade > 20h", metaValor: 1, metaTipo: "especial", pontos: 15 },
  { id: 207, categoria: "Produtividade", icone: "🌙", nome: "10x Coruja", descricao: "10 atividades após as 20h", meta: "10 ativ > 20h", metaValor: 10, metaTipo: "especial", pontos: 50 },
  { id: 208, categoria: "Produtividade", icone: "📆", nome: "Trabalhador de Sábado", descricao: "Trabalhe em 4 sábados", meta: "4 sábados", metaValor: 4, metaTipo: "dias", pontos: 50 },
  { id: 209, categoria: "Produtividade", icone: "📆", nome: "Trabalhador de Domingo", descricao: "Trabalhe em 4 domingos", meta: "4 domingos", metaValor: 4, metaTipo: "dias", pontos: 75 },
  { id: 210, categoria: "Produtividade", icone: "🔄", nome: "Multitarefa", descricao: "5 tipos de atividade em um dia", meta: "5 tipos/dia", metaValor: 5, metaTipo: "especial", pontos: 40 },
  { id: 211, categoria: "Produtividade", icone: "🔄", nome: "Super Multitarefa", descricao: "5 tipos de atividade por 5 dias", meta: "5 tipos x 5 dias", metaValor: 5, metaTipo: "especial", pontos: 100 },
  { id: 212, categoria: "Produtividade", icone: "📈", nome: "Crescimento Semanal", descricao: "Melhore performance vs semana anterior", meta: "+10% semana", metaValor: 10, metaTipo: "especial", pontos: 50 },
  { id: 213, categoria: "Produtividade", icone: "📈", nome: "Crescimento Mensal", descricao: "Melhore performance vs mês anterior", meta: "+10% mês", metaValor: 10, metaTipo: "especial", pontos: 100 },
  { id: 214, categoria: "Produtividade", icone: "🏃", nome: "Velocista", descricao: "Menor tempo médio de resposta da equipe", meta: "Menor tempo", metaValor: 1, metaTipo: "ranking", pontos: 100 },
  { id: 215, categoria: "Produtividade", icone: "🎯", nome: "Precisão", descricao: "Maior taxa de conversão da equipe", meta: "Maior taxa", metaValor: 1, metaTipo: "ranking", pontos: 150 },
  { id: 216, categoria: "Produtividade", icone: "💪", nome: "Consistente", descricao: "Mantenha produtividade por 30 dias", meta: "30 dias estável", metaValor: 30, metaTipo: "dias", pontos: 200 },
  { id: 217, categoria: "Produtividade", icone: "💪", nome: "Muito Consistente", descricao: "Mantenha produtividade por 60 dias", meta: "60 dias estável", metaValor: 60, metaTipo: "dias", pontos: 400 },
  { id: 218, categoria: "Produtividade", icone: "💪", nome: "Ultra Consistente", descricao: "Mantenha produtividade por 90 dias", meta: "90 dias estável", metaValor: 90, metaTipo: "dias", pontos: 600 },
  { id: 219, categoria: "Produtividade", icone: "🌟", nome: "Estrela do Dia", descricao: "Seja o mais produtivo do dia", meta: "#1 do dia", metaValor: 1, metaTipo: "ranking", pontos: 50 },
  { id: 220, categoria: "Produtividade", icone: "🌟", nome: "Estrela da Semana", descricao: "Seja o mais produtivo da semana", meta: "#1 da semana", metaValor: 1, metaTipo: "ranking", pontos: 150 },

  // Categoria 10: Especiais e Raras (30 conquistas)
  { id: 221, categoria: "Especiais e Raras", icone: "🌈", nome: "Arco-Íris", descricao: "Complete todas as categorias básicas", meta: "7 categorias", metaValor: 7, metaTipo: "conquistas", pontos: 500 },
  { id: 222, categoria: "Especiais e Raras", icone: "💎", nome: "Colecionador Bronze", descricao: "Desbloqueie 25 conquistas", meta: "25 conquistas", metaValor: 25, metaTipo: "conquistas", pontos: 100 },
  { id: 223, categoria: "Especiais e Raras", icone: "💎", nome: "Colecionador Prata", descricao: "Desbloqueie 50 conquistas", meta: "50 conquistas", metaValor: 50, metaTipo: "conquistas", pontos: 250 },
  { id: 224, categoria: "Especiais e Raras", icone: "💎", nome: "Colecionador Ouro", descricao: "Desbloqueie 100 conquistas", meta: "100 conquistas", metaValor: 100, metaTipo: "conquistas", pontos: 500 },
  { id: 225, categoria: "Especiais e Raras", icone: "💎", nome: "Colecionador Diamante", descricao: "Desbloqueie 150 conquistas", meta: "150 conquistas", metaValor: 150, metaTipo: "conquistas", pontos: 1000 },
  { id: 226, categoria: "Especiais e Raras", icone: "💎", nome: "Colecionador Mestre", descricao: "Desbloqueie 200 conquistas", meta: "200 conquistas", metaValor: 200, metaTipo: "conquistas", pontos: 2000 },
  { id: 227, categoria: "Especiais e Raras", icone: "💎", nome: "Colecionador Lendário", descricao: "Desbloqueie 250 conquistas", meta: "250 conquistas", metaValor: 250, metaTipo: "conquistas", pontos: 5000 },
  { id: 228, categoria: "Especiais e Raras", icone: "🎂", nome: "Aniversário 1 Mês", descricao: "Complete 1 mês no sistema", meta: "30 dias", metaValor: 30, metaTipo: "dias", pontos: 50 },
  { id: 229, categoria: "Especiais e Raras", icone: "🎂", nome: "Aniversário 3 Meses", descricao: "Complete 3 meses no sistema", meta: "90 dias", metaValor: 90, metaTipo: "dias", pontos: 100 },
  { id: 230, categoria: "Especiais e Raras", icone: "🎂", nome: "Aniversário 6 Meses", descricao: "Complete 6 meses no sistema", meta: "180 dias", metaValor: 180, metaTipo: "dias", pontos: 200 },
  { id: 231, categoria: "Especiais e Raras", icone: "🎂", nome: "Aniversário 1 Ano", descricao: "Complete 1 ano no sistema", meta: "365 dias", metaValor: 365, metaTipo: "dias", pontos: 500 },
  { id: 232, categoria: "Especiais e Raras", icone: "🎂", nome: "Aniversário 2 Anos", descricao: "Complete 2 anos no sistema", meta: "730 dias", metaValor: 730, metaTipo: "dias", pontos: 1000 },
  { id: 233, categoria: "Especiais e Raras", icone: "🔥", nome: "Fênix", descricao: "Volte ao top 3 após cair", meta: "Recuperação", metaValor: 1, metaTipo: "especial", pontos: 150 },
  { id: 234, categoria: "Especiais e Raras", icone: "🚀", nome: "Foguete", descricao: "Suba 5 posições no ranking em 1 semana", meta: "+5 posições", metaValor: 5, metaTipo: "especial", pontos: 100 },
  { id: 235, categoria: "Especiais e Raras", icone: "🚀", nome: "Super Foguete", descricao: "Suba 10 posições no ranking em 1 mês", meta: "+10 posições", metaValor: 10, metaTipo: "especial", pontos: 250 },
  { id: 236, categoria: "Especiais e Raras", icone: "🎪", nome: "Versátil", descricao: "Venda em 5 projetos diferentes", meta: "5 projetos", metaValor: 5, metaTipo: "especial", pontos: 200 },
  { id: 237, categoria: "Especiais e Raras", icone: "🎪", nome: "Super Versátil", descricao: "Venda em 10 projetos diferentes", meta: "10 projetos", metaValor: 10, metaTipo: "especial", pontos: 400 },
  { id: 238, categoria: "Especiais e Raras", icone: "🏅", nome: "Medalha de Ouro", descricao: "Seja campeão 3 meses seguidos", meta: "3x campeão", metaValor: 3, metaTipo: "streak", pontos: 1000 },
  { id: 239, categoria: "Especiais e Raras", icone: "🏅", nome: "Medalha de Platina", descricao: "Seja campeão 6 meses seguidos", meta: "6x campeão", metaValor: 6, metaTipo: "streak", pontos: 2500 },
  { id: 240, categoria: "Especiais e Raras", icone: "👑", nome: "Rei do Trimestre", descricao: "Maior VGV do trimestre", meta: "#1 trimestre", metaValor: 1, metaTipo: "ranking", pontos: 1000 },
  { id: 241, categoria: "Especiais e Raras", icone: "👑", nome: "Rei do Semestre", descricao: "Maior VGV do semestre", meta: "#1 semestre", metaValor: 1, metaTipo: "ranking", pontos: 2500 },
  { id: 242, categoria: "Especiais e Raras", icone: "👑", nome: "Rei do Ano", descricao: "Maior VGV do ano", meta: "#1 ano", metaValor: 1, metaTipo: "ranking", pontos: 5000 },
  { id: 243, categoria: "Especiais e Raras", icone: "🌟", nome: "Perfeição Diária", descricao: "100% das metas diárias", meta: "100% dia", metaValor: 100, metaTipo: "especial", pontos: 100 },
  { id: 244, categoria: "Especiais e Raras", icone: "🌟", nome: "Perfeição Semanal", descricao: "100% das metas semanais", meta: "100% semana", metaValor: 100, metaTipo: "especial", pontos: 300 },
  { id: 245, categoria: "Especiais e Raras", icone: "🌟", nome: "Perfeição Mensal", descricao: "100% das metas mensais", meta: "100% mês", metaValor: 100, metaTipo: "especial", pontos: 750 },
  { id: 246, categoria: "Especiais e Raras", icone: "🎖️", nome: "Veterano", descricao: "500 leads trabalhados", meta: "500 leads", metaValor: 500, metaTipo: "especial", pontos: 500 },
  { id: 247, categoria: "Especiais e Raras", icone: "🎖️", nome: "Super Veterano", descricao: "1000 leads trabalhados", meta: "1000 leads", metaValor: 1000, metaTipo: "especial", pontos: 1000 },
  { id: 248, categoria: "Especiais e Raras", icone: "🎖️", nome: "Lenda", descricao: "2500 leads trabalhados", meta: "2500 leads", metaValor: 2500, metaTipo: "especial", pontos: 2500 },
  { id: 249, categoria: "Especiais e Raras", icone: "🏆", nome: "Hall da Fama", descricao: "Entre no hall da fama", meta: "Critérios especiais", metaValor: 1, metaTipo: "especial", pontos: 5000 },
  { id: 250, categoria: "Especiais e Raras", icone: "👑", nome: "Lenda Viva", descricao: "Desbloqueie todas as conquistas", meta: "250 conquistas", metaValor: 250, metaTipo: "conquistas", pontos: 10000 },
];

// Sistema de Níveis
export const NIVEIS = [
  { nivel: 1, pontos: 0, titulo: "Novato" },
  { nivel: 2, pontos: 100, titulo: "Iniciante" },
  { nivel: 3, pontos: 250, titulo: "Aprendiz" },
  { nivel: 4, pontos: 500, titulo: "Praticante" },
  { nivel: 5, pontos: 1000, titulo: "Competente" },
  { nivel: 6, pontos: 2000, titulo: "Proficiente" },
  { nivel: 7, pontos: 3500, titulo: "Experiente" },
  { nivel: 8, pontos: 5000, titulo: "Avançado" },
  { nivel: 9, pontos: 7500, titulo: "Expert" },
  { nivel: 10, pontos: 10000, titulo: "Mestre" },
  { nivel: 11, pontos: 15000, titulo: "Grão-Mestre" },
  { nivel: 12, pontos: 20000, titulo: "Campeão" },
  { nivel: 13, pontos: 30000, titulo: "Elite" },
  { nivel: 14, pontos: 50000, titulo: "Lendário" },
  { nivel: 15, pontos: 85510, titulo: "Lenda Viva" },
];

// Função para obter nível baseado nos pontos
export function getNivelAtual(pontos: number): { nivel: number; titulo: string; pontosProximo: number; progresso: number } {
  let nivelAtual = NIVEIS[0];
  let proximoNivel = NIVEIS[1];
  
  for (let i = NIVEIS.length - 1; i >= 0; i--) {
    if (pontos >= NIVEIS[i].pontos) {
      nivelAtual = NIVEIS[i];
      proximoNivel = NIVEIS[i + 1] || NIVEIS[i];
      break;
    }
  }
  
  const pontosNoNivel = pontos - nivelAtual.pontos;
  const pontosParaProximo = proximoNivel.pontos - nivelAtual.pontos;
  const progresso = pontosParaProximo > 0 ? (pontosNoNivel / pontosParaProximo) * 100 : 100;
  
  return {
    nivel: nivelAtual.nivel,
    titulo: nivelAtual.titulo,
    pontosProximo: proximoNivel.pontos,
    progresso: Math.min(progresso, 100)
  };
}

// Categorias disponíveis
export const CATEGORIAS = [
  "Primeiros Passos",
  "Mestre das Ligações",
  "Mestre do WhatsApp",
  "Agendador Profissional",
  "Visitador Expert",
  "Documentador",
  "Vendedor Campeão",
  "Metas e Objetivos",
  "Produtividade",
  "Especiais e Raras"
];
